packages:
  - apps/*
  - packages/*
  - examples/*

catalog:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.7
  '@vitejs/plugin-react': 6.1.1
  react: 19.2.8
  react-dom: 19.2.8
  vite: 8.2.2

strictPeerDependencies: true
saveExact: true
onlyBuiltDependencies:
  - esbuild
  - ffmpeg-static
